local_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: prefect
      password: test-password # @TODO secret
      port: 5432
      dbname: prefect_server
      schema: staging
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1